apiVersion: v1
kind: Pod
metadata:
  name: variables-pod
spec:
  containers:
    - name: variables-busybox
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "echo $(MYPLANE) $(MYCARBRAND)" ]
      env:
        - name: MYPLANE
          valueFrom:
            configMapKeyRef:
              name: my-config-map-1
              key: PLANE_BRAND
        - name: MYCARBRAND
          valueFrom:
            configMapKeyRef:
              name: my-config-map
              key: car.brand
  restartPolicy: Never
